/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaprojet1;


import javax.swing.table.DefaultTableModel;
import java.awt.Color;
/**
 
 * @author adibm
 */
public class Accueil extends javax.swing.JFrame {
public void appliquerLeTheme() {
    // 1. On récupère les couleurs statiques depuis la classe Parametre
    java.awt.Color fond = Parametre.isDark ? Parametre.bgDark : Parametre.monFondOriginal;
    java.awt.Color texte = Parametre.isDark ? Parametre.fgDark : Parametre.monTexteOriginal;

    // 2. On applique au conteneur principal (le panel qui couvre tout)
    jPanel1.setBackground(fond);
    jPanel2.setBackground(fond);

    // 3. On applique à TOUS les labels, boutons et radios de CETTE interface
    // C'est cette partie qui change selon le nom de tes composants
    jLabeltitre.setForeground(texte); 
    jLabel1.setForeground(texte);
    jLabel5.setForeground(texte);
    
    
    
    // 4. On force le rafraîchissement visuel
    this.repaint();
}
    /**
     * Creates new form int1
     */
    public Accueil() {
        initComponents();
        appliquerLeTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonmatiere = new javax.swing.JButton();
        jButtonetudiant = new javax.swing.JButton();
        jButtonmoy = new javax.swing.JButton();
        jButtonnotes = new javax.swing.JButton();
        jButtonquitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelpara = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabeltitre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 235, 255));

        jPanel2.setBackground(new java.awt.Color(237, 243, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonmatiere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/mat.png"))); // NOI18N
        jButtonmatiere.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmatiere.setMaximumSize(new java.awt.Dimension(123, 26));
        jButtonmatiere.setMinimumSize(new java.awt.Dimension(123, 26));
        jButtonmatiere.setPreferredSize(new java.awt.Dimension(200, 88));
        jButtonmatiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonmatiereMouseClicked(evt);
            }
        });
        jButtonmatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmatiereActionPerformed(evt);
            }
        });

        jButtonetudiant.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButtonetudiant.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jButtonetudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/et.png"))); // NOI18N
        jButtonetudiant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonetudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonetudiantMouseClicked(evt);
            }
        });
        jButtonetudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonetudiantActionPerformed(evt);
            }
        });

        jButtonmoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/moy.png"))); // NOI18N
        jButtonmoy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmoy.setMaximumSize(new java.awt.Dimension(123, 26));
        jButtonmoy.setMinimumSize(new java.awt.Dimension(123, 26));
        jButtonmoy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonmoyMouseClicked(evt);
            }
        });
        jButtonmoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmoyActionPerformed(evt);
            }
        });

        jButtonnotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/nt.png"))); // NOI18N
        jButtonnotes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonnotes.setMaximumSize(new java.awt.Dimension(123, 26));
        jButtonnotes.setMinimumSize(new java.awt.Dimension(123, 26));
        jButtonnotes.setPreferredSize(new java.awt.Dimension(123, 26));
        jButtonnotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonnotesMouseClicked(evt);
            }
        });
        jButtonnotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnotesActionPerformed(evt);
            }
        });

        jButtonquitter.setBackground(new java.awt.Color(214, 214, 231));
        jButtonquitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonquitter.setForeground(new java.awt.Color(69, 102, 163));
        jButtonquitter.setText("Quitter");
        jButtonquitter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonquitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonquitterMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Bienvenue ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 102, 193));
        jLabel2.setText("Gérer facilement vos étudients, matiéres et notes");

        jLabelpara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/parametre1.png"))); // NOI18N
        jLabelpara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelparaMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("paramétre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addComponent(jButtonnotes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelpara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonetudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonmatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonmoy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(150, 150, 150))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonetudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonmatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelpara, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonnotes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonmoy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabeltitre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabeltitre.setForeground(new java.awt.Color(0, 0, 102));
        jLabeltitre.setText("Gestion des Etudiants & Notes");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/student2.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabeltitre)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonquitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonquitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonquitterMouseClicked

    private void jButtonnotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnotesActionPerformed

    }//GEN-LAST:event_jButtonnotesActionPerformed

    private void jButtonnotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonnotesMouseClicked
        try {
            // 1. On récupère les modèles de données des tables déjà ouvertes
            // Remplace 'jTableetudiant' et 'jTablemat' par tes vrais noms de variables
            DefaultTableModel etuModel = (DefaultTableModel) Etudiant.jTableetudiant.getModel();
            DefaultTableModel matModel = (DefaultTableModel) Matiere.jTablemat.getModel();

            // 2. On crée la fenêtre Note en lui DONNANT ces modèles
            Note n = new Note(etuModel, matModel);

            // 3. On affiche la fenêtre
            n.setVisible(true);

        } catch (Exception e) {
            // Si les fenêtres Etudiant ou Matiere ne sont pas encore ouvertes,
            // on crée des modèles vides pour éviter que le programme plante.
            DefaultTableModel videE = new DefaultTableModel();
            DefaultTableModel videM = new DefaultTableModel();
            new Note(videE, videM).setVisible(true);
        }
    }//GEN-LAST:event_jButtonnotesMouseClicked

    private void jButtonmoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonmoyActionPerformed

    private void jButtonmoyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmoyMouseClicked
        new Moyenne().setVisible(true);
    }//GEN-LAST:event_jButtonmoyMouseClicked

    private void jButtonetudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonetudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonetudiantActionPerformed

    private void jButtonetudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonetudiantMouseClicked
        new Etudiant().setVisible(true);
    }//GEN-LAST:event_jButtonetudiantMouseClicked

    private void jButtonmatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmatiereActionPerformed

    }//GEN-LAST:event_jButtonmatiereActionPerformed

    private void jButtonmatiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmatiereMouseClicked
        new Matiere().setVisible(true);
    }//GEN-LAST:event_jButtonmatiereMouseClicked

    private void jLabelparaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelparaMouseClicked
        new Parametre().setVisible(true);
    }//GEN-LAST:event_jLabelparaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonetudiant;
    private javax.swing.JButton jButtonmatiere;
    private javax.swing.JButton jButtonmoy;
    private javax.swing.JButton jButtonnotes;
    private javax.swing.JButton jButtonquitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelpara;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
