/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaprojet1;
//!

import javax.swing.table.DefaultTableModel;
//!
import javax.swing.JOptionPane;


/**
 *
 * @author adibm
 */
public class Etudiant extends javax.swing.JFrame {
    public void appliquerLeTheme() {
    // 1. On récupère les couleurs statiques depuis la classe Parametre
    java.awt.Color fond = Parametre.isDark ? Parametre.bgDark : Parametre.monFondOriginal;
    java.awt.Color texte = Parametre.isDark ? Parametre.fgDark : Parametre.monTexteOriginal;

    // 2. On applique au conteneur principal (le panel qui couvre tout)
    jPanel1.setBackground(fond);
    jPanel2.setBackground(fond);

    // 3. On applique à TOUS les labels, boutons et radios de CETTE interface
    // C'est cette partie qui change selon le nom de tes composants
    jLabeletudiant.setForeground(texte); 
    jLabelprenomE.setForeground(texte);
    jLabelclasseE.setForeground(texte);
    jLabelnomE.setForeground(texte);
    
    
    // 4. On force le rafraîchissement visuel
    this.repaint();
}

    /**
     * Creates new form etudiant
     */
    public Etudiant() {
        initComponents();
        appliquerLeTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableetudiant = new javax.swing.JTable();
        jButtonajouE = new javax.swing.JButton();
        jButtonmodE = new javax.swing.JButton();
        jButtonsupE = new javax.swing.JButton();
        jButtonvidE = new javax.swing.JButton();
        jTextFieldnomE = new javax.swing.JTextField();
        jTextFieldclasseE = new javax.swing.JTextField();
        jLabelnomE = new javax.swing.JLabel();
        jLabelclasseE = new javax.swing.JLabel();
        jTextFieldprenomE = new javax.swing.JTextField();
        jLabelprenomE = new javax.swing.JLabel();
        jButtonsuivet = new javax.swing.JButton();
        jLabeletudiant = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 235, 255));

        jPanel2.setBackground(new java.awt.Color(237, 243, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableetudiant.setBackground(new java.awt.Color(226, 228, 255));
        jTableetudiant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTableetudiant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableetudiant.setForeground(new java.awt.Color(0, 0, 51));
        jTableetudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Classe"
            }
        ));
        jTableetudiant.setRowHeight(25);
        jTableetudiant.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableetudiant.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableetudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableetudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableetudiant);

        jButtonajouE.setBackground(new java.awt.Color(46, 204, 113));
        jButtonajouE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonajouE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonajouE.setText("Ajouter");
        jButtonajouE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonajouE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonajouEMouseClicked(evt);
            }
        });
        jButtonajouE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonajouEActionPerformed(evt);
            }
        });

        jButtonmodE.setBackground(new java.awt.Color(243, 156, 18));
        jButtonmodE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonmodE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonmodE.setText("Modifier");
        jButtonmodE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmodE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonmodEMouseClicked(evt);
            }
        });
        jButtonmodE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodEActionPerformed(evt);
            }
        });

        jButtonsupE.setBackground(new java.awt.Color(231, 76, 60));
        jButtonsupE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsupE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsupE.setText("Supprimer");
        jButtonsupE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsupE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsupEMouseClicked(evt);
            }
        });
        jButtonsupE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupEActionPerformed(evt);
            }
        });

        jButtonvidE.setBackground(new java.awt.Color(204, 204, 204));
        jButtonvidE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonvidE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonvidE.setText("Vider");
        jButtonvidE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonvidE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonvidEMouseClicked(evt);
            }
        });

        jLabelnomE.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelnomE.setForeground(new java.awt.Color(0, 0, 102));
        jLabelnomE.setText("Nom :");

        jLabelclasseE.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelclasseE.setForeground(new java.awt.Color(0, 0, 102));
        jLabelclasseE.setText("Classe :");

        jTextFieldprenomE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprenomEActionPerformed(evt);
            }
        });

        jLabelprenomE.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelprenomE.setForeground(new java.awt.Color(0, 0, 102));
        jLabelprenomE.setText("Prenom :");

        jButtonsuivet.setBackground(new java.awt.Color(214, 214, 231));
        jButtonsuivet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsuivet.setForeground(new java.awt.Color(69, 102, 163));
        jButtonsuivet.setText("suivant >>");
        jButtonsuivet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsuivet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsuivetMouseClicked(evt);
            }
        });
        jButtonsuivet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuivetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonajouE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonmodE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsupE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonvidE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelprenomE)
                            .addComponent(jLabelnomE)
                            .addComponent(jLabelclasseE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldnomE, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldprenomE, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldclasseE, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonsuivet, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnomE)
                    .addComponent(jTextFieldnomE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelprenomE)
                    .addComponent(jTextFieldprenomE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelclasseE)
                    .addComponent(jTextFieldclasseE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonajouE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonmodE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsupE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonvidE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsuivet)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabeletudiant.setBackground(new java.awt.Color(255, 255, 255));
        jLabeletudiant.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabeletudiant.setForeground(new java.awt.Color(0, 0, 102));
        jLabeletudiant.setText("Gestion Etudiants");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/student2.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeletudiant)
                .addGap(192, 192, 192))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabeletudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonajouEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonajouEMouseClicked
        String nom = jTextFieldnomE.getText().trim();
    String prenom = jTextFieldprenomE.getText().trim();
    String classe = jTextFieldclasseE.getText().trim();

    //  Vérif champs vides
    if(nom.equals("") || prenom.equals("") || classe.equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs");
        return;
    }

    //  Vérif nom / prenom (pas de chiffres)
    if(!nom.matches("[a-zA-Z ]+")){
        JOptionPane.showMessageDialog(this, "Nom invalide (pas de chiffres)");
        return;
    }

    if(!prenom.matches("[a-zA-Z ]+")){
        JOptionPane.showMessageDialog(this, "Prénom invalide (pas de chiffres)");
        return;
    }

    //  Ajouter dans JTable
    DefaultTableModel model = (DefaultTableModel) jTableetudiant.getModel();

    model.addRow(new Object[]{nom, prenom, classe});

    //  Envoyer vers Note (comboBox)
    String nomComplet = nom + " " + prenom;

    Note.addEtudiant(nomComplet);

    // vider champs
    jTextFieldnomE.setText("");
    jTextFieldprenomE.setText("");
    jTextFieldclasseE.setText("");

    }//GEN-LAST:event_jButtonajouEMouseClicked

    private void jButtonmodEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmodEMouseClicked
       //!
        int selected=jTableetudiant.getSelectedRow();
        //!
        if(selected!=-1){
            //!
            jTableetudiant.setValueAt(jTextFieldnomE.getText(),selected,0);
            //!
            jTableetudiant.setValueAt(jTextFieldprenomE.getText(),selected,1);
            //!
            jTableetudiant.setValueAt(jTextFieldclasseE.getText(),selected,2);
            
        }else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une ligne pour modifier");
    }
    }//GEN-LAST:event_jButtonmodEMouseClicked

    private void jButtonsupEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsupEMouseClicked
        //!
        int selected=jTableetudiant.getSelectedRow();
        //!
        if(selected != -1){
            //!
            String nomComplet= jTableetudiant.getValueAt(selected,0)+" "+jTableetudiant.getValueAt(selected, 1);
            //!
            DefaultTableModel model=(DefaultTableModel)jTableetudiant.getModel();
            //!
            model.removeRow(selected);
            //!
            Note.removeEtudiantFromCombo( nomComplet);
        } else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une ligne pour supprimer");
    }
    }//GEN-LAST:event_jButtonsupEMouseClicked

    private void jButtonvidEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonvidEMouseClicked
        //!
        jTextFieldnomE.setText("");
        jTextFieldprenomE.setText("");
        jTextFieldclasseE.setText("");
    }//GEN-LAST:event_jButtonvidEMouseClicked

    private void jButtonajouEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonajouEActionPerformed
        
    }                                            

    private void jButtonvidMActionPerformed(java.awt.event.ActionEvent evt) {                                            
                                 

    }//GEN-LAST:event_jButtonajouEActionPerformed

    private void jButtonsupEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsupEActionPerformed

    private void jButtonmodEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonmodEActionPerformed

    private void jTableetudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableetudiantMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableetudiantMouseClicked

    private void jTextFieldprenomEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprenomEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprenomEActionPerformed

    private void jButtonsuivetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsuivetMouseClicked
        new Matiere().setVisible(true);
    }//GEN-LAST:event_jButtonsuivetMouseClicked

    private void jButtonsuivetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuivetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsuivetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonajouE;
    private javax.swing.JButton jButtonmodE;
    private javax.swing.JButton jButtonsuivet;
    private javax.swing.JButton jButtonsupE;
    private javax.swing.JButton jButtonvidE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelclasseE;
    private javax.swing.JLabel jLabeletudiant;
    private javax.swing.JLabel jLabelnomE;
    private javax.swing.JLabel jLabelprenomE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableetudiant;
    private javax.swing.JTextField jTextFieldclasseE;
    private javax.swing.JTextField jTextFieldnomE;
    private javax.swing.JTextField jTextFieldprenomE;
    // End of variables declaration//GEN-END:variables
}
