/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaprojet1;

 import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
 
public class Matiere extends javax.swing.JFrame {
public void appliquerLeTheme() {
    // 1. On récupère les couleurs statiques depuis la classe Parametre
    java.awt.Color fond = Parametre.isDark ? Parametre.bgDark : Parametre.monFondOriginal;
    java.awt.Color texte = Parametre.isDark ? Parametre.fgDark : Parametre.monTexteOriginal;

    // 2. On applique au conteneur principal (le panel qui couvre tout)
    jPanel1.setBackground(fond);
    jPanel2.setBackground(fond);

    // 3. On applique à TOUS les labels, boutons et radios de CETTE interface
    // C'est cette partie qui change selon le nom de tes composants
    jLabelnommat.setForeground(texte); 
    jLabelmatiere.setForeground(texte);
    jLabelcoef.setForeground(texte);
    
    
    
    // 4. On force le rafraîchissement visuel
    this.repaint();
}
    /**
     * Creates new form int2
     */
    public Matiere() {
        initComponents();
        appliquerLeTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnommat = new javax.swing.JLabel();
        jTextnommat = new javax.swing.JTextField();
        jLabelcoef = new javax.swing.JLabel();
        jTextcoef = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablemat = new javax.swing.JTable();
        jButtonajouM = new javax.swing.JButton();
        jButtonmodM = new javax.swing.JButton();
        jButtonsuppM = new javax.swing.JButton();
        jButtonvidM = new javax.swing.JButton();
        jButtonsuivmat = new javax.swing.JButton();
        jLabelmatiere = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 235, 255));

        jPanel2.setBackground(new java.awt.Color(237, 243, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelnommat.setBackground(new java.awt.Color(102, 102, 102));
        jLabelnommat.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelnommat.setForeground(new java.awt.Color(0, 0, 102));
        jLabelnommat.setText("Nom Matiere :");

        jTextnommat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnommatActionPerformed(evt);
            }
        });

        jLabelcoef.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelcoef.setForeground(new java.awt.Color(0, 0, 102));
        jLabelcoef.setText("coef :");

        jTablemat.setBackground(new java.awt.Color(226, 228, 255));
        jTablemat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTablemat.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTablemat.setForeground(new java.awt.Color(102, 102, 102));
        jTablemat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Matiere", "Coef"
            }
        ));
        jTablemat.setShowGrid(true);
        jTablemat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablematMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablemat);

        jButtonajouM.setBackground(new java.awt.Color(46, 204, 113));
        jButtonajouM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonajouM.setForeground(new java.awt.Color(255, 255, 255));
        jButtonajouM.setText("Ajouter");
        jButtonajouM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonajouM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonajouMMouseClicked(evt);
            }
        });
        jButtonajouM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonajouMActionPerformed(evt);
            }
        });

        jButtonmodM.setBackground(new java.awt.Color(243, 156, 18));
        jButtonmodM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonmodM.setForeground(new java.awt.Color(255, 255, 255));
        jButtonmodM.setText("Modifier");
        jButtonmodM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmodM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonmodMMouseClicked(evt);
            }
        });
        jButtonmodM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodMActionPerformed(evt);
            }
        });

        jButtonsuppM.setBackground(new java.awt.Color(231, 76, 60));
        jButtonsuppM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsuppM.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsuppM.setText("Supprimer");
        jButtonsuppM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsuppM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsuppMMouseClicked(evt);
            }
        });
        jButtonsuppM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuppMActionPerformed(evt);
            }
        });

        jButtonvidM.setBackground(new java.awt.Color(204, 204, 204));
        jButtonvidM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonvidM.setForeground(new java.awt.Color(255, 255, 255));
        jButtonvidM.setText("Vider");
        jButtonvidM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonvidM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonvidMMouseClicked(evt);
            }
        });
        jButtonvidM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvidMActionPerformed(evt);
            }
        });

        jButtonsuivmat.setBackground(new java.awt.Color(214, 214, 231));
        jButtonsuivmat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsuivmat.setForeground(new java.awt.Color(69, 102, 163));
        jButtonsuivmat.setText("suivant >>");
        jButtonsuivmat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsuivmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsuivmatMouseClicked(evt);
            }
        });
        jButtonsuivmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuivmatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonajouM, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonmodM, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsuppM, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonvidM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelnommat)
                                .addGap(27, 27, 27)
                                .addComponent(jTextnommat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabelcoef)
                                .addGap(30, 30, 30)
                                .addComponent(jTextcoef, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonsuivmat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnommat)
                    .addComponent(jTextnommat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcoef)
                    .addComponent(jTextcoef, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonajouM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonmodM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsuppM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonvidM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsuivmat)
                .addGap(15, 15, 15))
        );

        jLabelmatiere.setBackground(new java.awt.Color(51, 51, 51));
        jLabelmatiere.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelmatiere.setForeground(new java.awt.Color(0, 0, 102));
        jLabelmatiere.setText("Gestion Matières");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/student2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelmatiere)
                .addGap(198, 198, 198))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelmatiere)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonmodMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodMActionPerformed
         
    }//GEN-LAST:event_jButtonmodMActionPerformed

    private void jButtonsuppMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuppMActionPerformed
        
    }//GEN-LAST:event_jButtonsuppMActionPerformed

    private void jTextnommatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnommatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnommatActionPerformed

    private void jButtonajouMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonajouMActionPerformed
           
    }//GEN-LAST:event_jButtonajouMActionPerformed

    private void jButtonvidMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvidMActionPerformed
       
    }//GEN-LAST:event_jButtonvidMActionPerformed

    private void jButtonajouMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonajouMMouseClicked
        String nom = jTextnommat.getText().trim();
    String coefText = jTextcoef.getText().trim();

    //Vérifier champs vides
    if(nom.equals("") || coefText.equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs");
        return;
    }

    // Vérifier nom 
    if(!nom.matches("[a-zA-Z ]+")){
        JOptionPane.showMessageDialog(this, "Nom matière invalide !");
        return;
    }

    //Vérifier coef
    float coef;
    try {
        coef = Float.parseFloat(coefText);

        if(coef <= 0 || coef >+20){
            JOptionPane.showMessageDialog(this, "Coef entre 1 et 5");
            return;
        }

    } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Coef doit être un nombre !");
        return;
    }

    //  Vérifier doublon matière
    DefaultTableModel model = (DefaultTableModel) jTablemat.getModel();

    for(int i = 0; i < model.getRowCount(); i++){
        String exist = model.getValueAt(i, 0).toString();
        if(exist.equalsIgnoreCase(nom)){
            JOptionPane.showMessageDialog(this, "Matière déjà existe!");
            return;
        }
    }

    // Ajouter dans table
    model.addRow(new Object[]{nom, coef});

    // Ajouter dans liste
    String matiere = nom + " " + coef;
    Note.addMatiere(matiere);

    // vider champs
    jTextnommat.setText("");
    jTextcoef.setText("");
    }//GEN-LAST:event_jButtonajouMMouseClicked

    private void jButtonvidMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonvidMMouseClicked
        jTextnommat.setText("");
        jTextcoef.setText("");
    }//GEN-LAST:event_jButtonvidMMouseClicked

    private void jButtonmodMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmodMMouseClicked
//!
        int selected=jTablemat.getSelectedRow();
        //!
        if(selected!=-1){
            //!
            jTablemat.setValueAt(jTextnommat.getText(),selected,0);
            //!
            jTablemat.setValueAt(jTextcoef.getText(),selected,1);
            //!
            
        }else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une ligne pour modifier");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonmodMMouseClicked

    private void jButtonsuppMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsuppMMouseClicked
int selected=jTablemat.getSelectedRow();
        //!
        if(selected != -1){
            //!
            String matiere= jTablemat.getValueAt(selected,0)+" "+jTablemat.getValueAt(selected, 1);
            //!
            DefaultTableModel model=(DefaultTableModel)jTablemat.getModel();
            //!
            model.removeRow(selected);
            Note.removeEtudiantFromCombo( matiere);
        } else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une ligne pour supprimer");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsuppMMouseClicked

    private void jTablematMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablematMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablematMouseClicked

    private void jButtonsuivmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsuivmatMouseClicked
        try {
            // 1. On récupère les modèles de données des tables déjà ouvertes
            // Remplace 'jTableetudiant' et 'jTablemat' par tes vrais noms de variables
            DefaultTableModel etuModel = (DefaultTableModel) Etudiant.jTableetudiant.getModel();
            DefaultTableModel matModel = (DefaultTableModel) Matiere.jTablemat.getModel();

            // 2. On crée la fenêtre Note en lui DONNANT ces modèles
            Note n = new Note(etuModel, matModel);

            // 3. On affiche la fenêtre
            n.setVisible(true);

        } catch (Exception e) {
            // Si les fenêtres Etudiant ou Matiere ne sont pas encore ouvertes,
            // on crée des modèles vides pour éviter que le programme plante.
            DefaultTableModel videE = new DefaultTableModel();
            DefaultTableModel videM = new DefaultTableModel();
            new Note(videE, videM).setVisible(true);
        }
    }//GEN-LAST:event_jButtonsuivmatMouseClicked

    private void jButtonsuivmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuivmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsuivmatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matiere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonajouM;
    private javax.swing.JButton jButtonmodM;
    private javax.swing.JButton jButtonsuivmat;
    private javax.swing.JButton jButtonsuppM;
    private javax.swing.JButton jButtonvidM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelcoef;
    private javax.swing.JLabel jLabelmatiere;
    private javax.swing.JLabel jLabelnommat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTablemat;
    private javax.swing.JTextField jTextcoef;
    private javax.swing.JTextField jTextnommat;
    // End of variables declaration//GEN-END:variables
}
