/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaprojet1;
//!
import javax.swing.table.DefaultTableModel;
//!
import javax.swing.JOptionPane;
/**
 *
 * @author adibm
 */
public class Note extends javax.swing.JFrame {
    // 1. CONSTRUCTEUR MODIFIÉ (Il reçoit les données de l'Accueil)
    public Note(DefaultTableModel modeleEtu, DefaultTableModel modeleMat) {
        initComponents();
        appliquerLeTheme();
        
        // Remplir la liste des étudiants avec les données reçues
        jComboBoxetudiantN.removeAllItems();
        jComboBoxetudiantN.addItem("");
        if (modeleEtu != null) {
            for (int i = 0; i < modeleEtu.getRowCount(); i++) {
                String nom = modeleEtu.getValueAt(i, 0).toString();
                String prenom = modeleEtu.getValueAt(i, 1).toString();
                jComboBoxetudiantN.addItem(nom + " " + prenom);
            }
        }

        // Remplir la liste des matières avec les données reçues
        jComboBoxmatN.removeAllItems();
        jComboBoxmatN.addItem("");
        if (modeleMat != null) {
            for (int i = 0; i < modeleMat.getRowCount(); i++) {
                jComboBoxmatN.addItem(modeleMat.getValueAt(i, 0).toString());
            }
        }
        
        // Configuration du MouseListener pour la modification
        jTablenote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selected = jTablenote.getSelectedRow();
                if (selected != -1) {
                    jComboBoxetudiantN.setSelectedItem(jTablenote.getValueAt(selected, 0).toString());
                    jComboBoxmatN.setSelectedItem(jTablenote.getValueAt(selected, 1).toString());
                    jTextFieldnoteN.setText(jTablenote.getValueAt(selected, 2).toString());
                }
            }
        });

    }
    // ------------------------------------------------------------------
public void appliquerLeTheme() {
    // 1. On récupère les couleurs statiques depuis la classe Parametre
    java.awt.Color fond = Parametre.isDark ? Parametre.bgDark : Parametre.monFondOriginal;
    java.awt.Color texte = Parametre.isDark ? Parametre.fgDark : Parametre.monTexteOriginal;

    // 2. On applique au conteneur principal (le panel qui couvre tout)
    jPanel1.setBackground(fond);
    jPanel2.setBackground(fond);

    // 3. On applique à TOUS les labels, boutons et radios de CETTE interface
    // C'est cette partie qui change selon le nom de tes composants
    jLabeletudianN.setForeground(texte); 
    jLabelmatN.setForeground(texte);
    jLabelnoteN.setForeground(texte);
    jLabel1.setForeground(texte);
    
    
    
    // 4. On force le rafraîchissement visuel
    this.repaint();
}
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxetudiantN = new javax.swing.JComboBox<>();
        jComboBoxmatN = new javax.swing.JComboBox<>();
        jTextFieldnoteN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablenote = new javax.swing.JTable();
        jButtonajouN = new javax.swing.JButton();
        jButtonmodN = new javax.swing.JButton();
        jButtonsupN = new javax.swing.JButton();
        jButtonvidN = new javax.swing.JButton();
        jLabeletudianN = new javax.swing.JLabel();
        jLabelmatN = new javax.swing.JLabel();
        jLabelnoteN = new javax.swing.JLabel();
        jButtonsuivnote = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 235, 255));

        jPanel2.setBackground(new java.awt.Color(237, 243, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxetudiantN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxetudiantNActionPerformed(evt);
            }
        });

        jComboBoxmatN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxmatN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmatNActionPerformed(evt);
            }
        });

        jTextFieldnoteN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnoteNActionPerformed(evt);
            }
        });

        jTablenote.setBackground(new java.awt.Color(226, 228, 255));
        jTablenote.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTablenote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Etudiant", "Matiere", "Note"
            }
        ));
        jTablenote.setShowGrid(true);
        jScrollPane1.setViewportView(jTablenote);

        jButtonajouN.setBackground(new java.awt.Color(46, 204, 113));
        jButtonajouN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonajouN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonajouN.setText("Ajouter");
        jButtonajouN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonajouN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonajouNMouseClicked(evt);
            }
        });

        jButtonmodN.setBackground(new java.awt.Color(243, 156, 18));
        jButtonmodN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonmodN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonmodN.setText("Modifier");
        jButtonmodN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmodN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonmodNMouseClicked(evt);
            }
        });

        jButtonsupN.setBackground(new java.awt.Color(231, 76, 60));
        jButtonsupN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsupN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsupN.setText("Supprimer");
        jButtonsupN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsupN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsupNMouseClicked(evt);
            }
        });
        jButtonsupN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupNActionPerformed(evt);
            }
        });

        jButtonvidN.setBackground(new java.awt.Color(204, 204, 204));
        jButtonvidN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonvidN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonvidN.setText("Vider");
        jButtonvidN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonvidN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonvidNMouseClicked(evt);
            }
        });
        jButtonvidN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvidNActionPerformed(evt);
            }
        });

        jLabeletudianN.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabeletudianN.setForeground(new java.awt.Color(0, 0, 102));
        jLabeletudianN.setText("Etudiant :");

        jLabelmatN.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelmatN.setForeground(new java.awt.Color(0, 0, 102));
        jLabelmatN.setText("Matiere :");

        jLabelnoteN.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelnoteN.setForeground(new java.awt.Color(0, 0, 102));
        jLabelnoteN.setText("Note :");

        jButtonsuivnote.setBackground(new java.awt.Color(214, 214, 231));
        jButtonsuivnote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsuivnote.setForeground(new java.awt.Color(69, 102, 163));
        jButtonsuivnote.setText("suivant >>");
        jButtonsuivnote.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsuivnote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsuivnoteMouseClicked(evt);
            }
        });
        jButtonsuivnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuivnoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonajouN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonmodN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonsupN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonvidN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabeletudianN)
                                    .addComponent(jLabelnoteN)
                                    .addComponent(jLabelmatN))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxmatN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxetudiantN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldnoteN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonsuivnote, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxetudiantN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeletudianN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelmatN)
                    .addComponent(jComboBoxmatN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnoteN)
                    .addComponent(jTextFieldnoteN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonmodN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonsupN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonvidN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonajouN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsuivnote)
                .addGap(9, 9, 9))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Gestion des Notes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/student2.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//!
    
//!  
public static void addEtudiant(String nomComplet) {
    if(jComboBoxetudiantN != null) { // check null
        jComboBoxetudiantN.addItem(nomComplet);
    }
}

public static void removeEtudiantFromCombo(String nomComplet) {
    if(jComboBoxetudiantN != null) { // check null
        jComboBoxetudiantN.removeItem(nomComplet);
    }
}
//* HOUNI MANAJEMTECH NBADEL DECLARATION DONC RAJA3THA M3ADECH STATIC
public static void addMatiere(String matiere) {
    if(jComboBoxmatN != null) {
    jComboBoxmatN.addItem(matiere);
}
}
public void removeMatiereFromCombo(String matiere) {
    jComboBoxmatN.removeItem(matiere);
}
//*
    private void jTextFieldnoteNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnoteNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnoteNActionPerformed

    private void jButtonsupNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsupNActionPerformed

    private void jButtonvidNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvidNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonvidNActionPerformed

    private void jComboBoxetudiantNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxetudiantNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxetudiantNActionPerformed

    private void jButtonajouNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonajouNMouseClicked
        //!                                          
    String etudiant = jComboBoxetudiantN.getSelectedItem() != null ? jComboBoxetudiantN.getSelectedItem().toString() : "";
    String matiere = jComboBoxmatN.getSelectedItem() != null ? jComboBoxmatN.getSelectedItem().toString() : "";
    String note = jTextFieldnoteN.getText();

    if(!etudiant.equals("") && !matiere.equals("") && !note.equals("")) {
        double n;
         //vérifier note (numérique)
    try {
        n=Double.parseDouble(note); // vérifie note
    } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "La note doit être un nombre !");
        return;
    }

    //vérifier intervalle note
    if(n < 0 || n > 20){
        JOptionPane.showMessageDialog(this, "Note entre 0 et 20 !");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTablenote.getModel();
    // ajout 
    model.addRow(new Object[]{etudiant, matiere, note});

    //vider champ
    jTextFieldnoteN.setText("");
    }
    }//GEN-LAST:event_jButtonajouNMouseClicked

    private void jButtonmodNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmodNMouseClicked
    //! 
        int selected = jTablenote.getSelectedRow();
    //!
        if(selected != -1){
    //!
            jTablenote.setValueAt(jComboBoxetudiantN.getSelectedItem(), selected, 0);
    //!
            jTablenote.setValueAt(jComboBoxmatN.getSelectedItem(), selected, 1);
    //!
            jTablenote.setValueAt(jTextFieldnoteN.getText(), selected, 2);
    } else {
    //!
    javax.swing.JOptionPane.showMessageDialog(null, "Sélectionnez une ligne pour modifier");
    }
    }//GEN-LAST:event_jButtonmodNMouseClicked

    private void jButtonsupNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsupNMouseClicked
    //!
        int selected = jTablenote.getSelectedRow();
    //!
        if(selected != -1){
    //!    
            ((DefaultTableModel) jTablenote.getModel()).removeRow(selected);
    //!
        } else {
    //!
            javax.swing.JOptionPane.showMessageDialog(null, "Sélectionnez une ligne pour supprimer");
    }
    }//GEN-LAST:event_jButtonsupNMouseClicked

    private void jButtonvidNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonvidNMouseClicked
       //!
        jTextFieldnoteN.setText("");
        //!
        jComboBoxetudiantN.setSelectedIndex(0);
        //!
        jComboBoxmatN.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonvidNMouseClicked

    private void jComboBoxmatNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmatNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmatNActionPerformed

    private void jButtonsuivnoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsuivnoteMouseClicked
        new Moyenne().setVisible(true);
    }//GEN-LAST:event_jButtonsuivnoteMouseClicked

    private void jButtonsuivnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuivnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsuivnoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
   DefaultTableModel videEtu = new DefaultTableModel();
                DefaultTableModel videMat = new DefaultTableModel();
                new Note(videEtu, videMat).setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonajouN;
    private javax.swing.JButton jButtonmodN;
    private javax.swing.JButton jButtonsuivnote;
    private javax.swing.JButton jButtonsupN;
    private javax.swing.JButton jButtonvidN;
    public static javax.swing.JComboBox<String> jComboBoxetudiantN;
    public static javax.swing.JComboBox<String> jComboBoxmatN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeletudianN;
    private javax.swing.JLabel jLabelmatN;
    private javax.swing.JLabel jLabelnoteN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTablenote;
    private javax.swing.JTextField jTextFieldnoteN;
    // End of variables declaration//GEN-END:variables
}