/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaprojet1;
import java.awt.Color;
/**
 *
 * @author adibm
 */
public class Parametre extends javax.swing.JFrame {
public static boolean isDark = false;

// Couleurs du mode Sombre
public static java.awt.Color bgDark = new java.awt.Color(0,73,147); // Bleu Marine
public static java.awt.Color fgDark = java.awt.Color.WHITE;

// Variables qui vont stocker tes couleurs choisies dans le Design
public static java.awt.Color monFondOriginal;
public static java.awt.Color monTexteOriginal;
    /**
     * Creates new form Parametre
     */
public void appliquerLeTheme() {
    if (isDark) {
        // Mode Sombre : On force le Bleu Marine et le Blanc
        jPanel1.setBackground(bgDark);
        jPanel2.setBackground(bgDark);
        jLabelparametre.setForeground(fgDark);
        jRadioSombre.setForeground(fgDark);
        jRadioSombre.setBackground(bgDark);
        jRadioClaire.setForeground(fgDark);
        jRadioClaire.setBackground(bgDark);
        jButtonappliP.setForeground(fgDark);
    } else {
        // Mode Clair : On remet EXACTEMENT tes couleurs du Design
        jPanel1.setBackground(monFondOriginal);
        jPanel2.setBackground(monFondOriginal);
        jLabelparametre.setForeground(monTexteOriginal);
        jRadioSombre.setForeground(monTexteOriginal);
        jRadioSombre.setBackground(monFondOriginal);
        jRadioClaire.setForeground(monTexteOriginal);
        jRadioClaire.setBackground(monFondOriginal);
        jButtonappliP.setForeground(monTexteOriginal);
    }
    
    this.repaint();
}
    public Parametre() {
        initComponents();
    // On mémorise les couleurs que tu as mises dans le Design NetBeans
    monFondOriginal = jPanel1.getBackground(); 
    monFondOriginal = jPanel2.getBackground(); 
    monTexteOriginal = jLabelparametre.getForeground();
    
    appliquerLeTheme();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonretourP = new javax.swing.JButton();
        jButtonappliP = new javax.swing.JButton();
        jLabelthemeP = new javax.swing.JLabel();
        jRadioSombre = new javax.swing.JRadioButton();
        jRadioClaire = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelparametre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 235, 255));

        jPanel2.setBackground(new java.awt.Color(237, 243, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(603, 260));

        jButtonretourP.setBackground(new java.awt.Color(204, 204, 204));
        jButtonretourP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonretourP.setForeground(new java.awt.Color(51, 51, 51));
        jButtonretourP.setText("Retourner");
        jButtonretourP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonretourP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonretourPMouseClicked(evt);
            }
        });

        jButtonappliP.setBackground(new java.awt.Color(254, 94, 94));
        jButtonappliP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonappliP.setForeground(new java.awt.Color(51, 51, 51));
        jButtonappliP.setText("Appliquer");
        jButtonappliP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonappliP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonappliPMouseClicked(evt);
            }
        });
        jButtonappliP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonappliPActionPerformed(evt);
            }
        });

        jLabelthemeP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelthemeP.setForeground(new java.awt.Color(69, 102, 193));
        jLabelthemeP.setText("Choisi le mode :");

        buttonGroup1.add(jRadioSombre);
        jRadioSombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioSombre.setText("Sombre ");
        jRadioSombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioClaire);
        jRadioClaire.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioClaire.setText("Claire");
        jRadioClaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioClaireActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/light.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/darck.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButtonappliP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButtonretourP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelthemeP, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioClaire, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioSombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelthemeP)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioSombre)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioClaire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonappliP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonretourP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaprojet1/image-java/student2.png"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabelparametre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelparametre.setForeground(new java.awt.Color(0, 0, 102));
        jLabelparametre.setText("Paramètres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelparametre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelparametre)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioClaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioClaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioClaireActionPerformed

    private void jRadioSombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSombreActionPerformed

    private void jButtonappliPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonappliPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonappliPActionPerformed

    private void jButtonappliPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonappliPMouseClicked
        // On met à jour la variable statique
        isDark = jRadioSombre.isSelected();

        // On applique le thème à la fenêtre Paramètre elle-même
        appliquerLeTheme();

    }//GEN-LAST:event_jButtonappliPMouseClicked

    private void jButtonretourPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonretourPMouseClicked
        new Accueil().setVisible(true);
    }//GEN-LAST:event_jButtonretourPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonappliP;
    private javax.swing.JButton jButtonretourP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelparametre;
    private javax.swing.JLabel jLabelthemeP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioClaire;
    private javax.swing.JRadioButton jRadioSombre;
    // End of variables declaration//GEN-END:variables
}
